--
-- SYS_LANGUAGE
--
INSERT INTO SYS_LANGUAGE (ID, CODE, DATE_MASK) VALUES (1, 'en-UK', 'MM/dd/yyyy');
INSERT INTO SYS_LANGUAGE (ID, CODE, DATE_MASK) VALUES (2, 'es-ES', 'dd/MM/yyyy');

--
-- SYS_LANGUAGE_LANG
--
INSERT INTO SYS_LANGUAGE_LANG (ID, TRANSLATION_ID, NAME) VALUES (1, 1, 'English');
INSERT INTO SYS_LANGUAGE_LANG (ID, TRANSLATION_ID, NAME) VALUES (1, 2, 'Inglés');
INSERT INTO SYS_LANGUAGE_LANG (ID, TRANSLATION_ID, NAME) VALUES (2, 1, 'Spanish');
INSERT INTO SYS_LANGUAGE_LANG (ID, TRANSLATION_ID, NAME) VALUES (2, 2, 'Español');

--
-- SYS_PERSON
--
INSERT INTO SYS_PERSON (ID, START_DATE, END_DATE) VALUES (1, CURRENT_TIMESTAMP, NULL);
INSERT INTO SYS_PERSON (ID, START_DATE, END_DATE) VALUES (2, CURRENT_TIMESTAMP, NULL);
INSERT INTO SYS_PERSON (ID, START_DATE, END_DATE) VALUES (3, CURRENT_TIMESTAMP, NULL);
INSERT INTO SYS_PERSON (ID, START_DATE, END_DATE) VALUES (4, CURRENT_TIMESTAMP, NULL);
INSERT INTO SYS_PERSON (ID, START_DATE, END_DATE) VALUES (5, CURRENT_TIMESTAMP, NULL);
INSERT INTO SYS_PERSON (ID, START_DATE, END_DATE) VALUES (6, CURRENT_TIMESTAMP, NULL);
INSERT INTO SYS_PERSON (ID, START_DATE, END_DATE) VALUES (7, CURRENT_TIMESTAMP, NULL);
INSERT INTO SYS_PERSON (ID, START_DATE, END_DATE) VALUES (8, CURRENT_TIMESTAMP, NULL);
INSERT INTO SYS_PERSON (ID, START_DATE, END_DATE) VALUES (9, CURRENT_TIMESTAMP, NULL);
INSERT INTO SYS_PERSON (ID, START_DATE, END_DATE) VALUES (10, CURRENT_TIMESTAMP, NULL);

--
-- SYS_PERSON
--
INSERT INTO SYS_PERSON_DATA (ID, NAME, LAST_NAME) VALUES (1, 'Juan', 'López González');
INSERT INTO SYS_PERSON_DATA (ID, NAME, LAST_NAME) VALUES (2, 'Pedro', 'Suárez Antúnez');
INSERT INTO SYS_PERSON_DATA (ID, NAME, LAST_NAME) VALUES (3, 'Alberto', 'Fuentes Guerrero');
INSERT INTO SYS_PERSON_DATA (ID, NAME, LAST_NAME) VALUES (4, 'José', 'García Pérez');
INSERT INTO SYS_PERSON_DATA (ID, NAME, LAST_NAME) VALUES (5, 'Luis', 'Albiol ');
INSERT INTO SYS_PERSON_DATA (ID, NAME, LAST_NAME) VALUES (6, 'Félix', 'Benavente Zambrano');
INSERT INTO SYS_PERSON_DATA (ID, NAME, LAST_NAME) VALUES (7, 'Cristina', 'Sánchez López');
INSERT INTO SYS_PERSON_DATA (ID, NAME, LAST_NAME) VALUES (8, 'Lucía', 'Pérez Cordero');
INSERT INTO SYS_PERSON_DATA (ID, NAME, LAST_NAME) VALUES (9, 'Irene', 'Fernández Saavedra');
INSERT INTO SYS_PERSON_DATA (ID, NAME, LAST_NAME) VALUES (10, 'Ángela', 'Álvarez Ventura');

--
-- SEC_USER
--

INSERT INTO SEC_USER (ID, LOGIN, PASSWORD) VALUES (1, 'user1', 'user1');
INSERT INTO SEC_USER (ID, LOGIN, PASSWORD) VALUES (2, 'user2', 'user2');
INSERT INTO SEC_USER (ID, LOGIN, PASSWORD) VALUES (3, 'user3', 'user3');
INSERT INTO SEC_USER (ID, LOGIN, PASSWORD) VALUES (4, 'user4', 'user4');
INSERT INTO SEC_USER (ID, LOGIN, PASSWORD) VALUES (5, 'user5', 'user5');

--
-- CUST_CUSTOMER
--
INSERT INTO CUST_CUSTOMER (ID) VALUES (6);
INSERT INTO CUST_CUSTOMER (ID) VALUES (7);
INSERT INTO CUST_CUSTOMER (ID) VALUES (8);
INSERT INTO CUST_CUSTOMER (ID) VALUES (9);
INSERT INTO CUST_CUSTOMER (ID) VALUES (10);
