--
-- CUST_CUSTOMER
--
INSERT INTO CUST_CUSTOMER (ID, NAME, LAST_NAME) VALUES (1, 'Juan', 'López González');
INSERT INTO CUST_CUSTOMER (ID, NAME, LAST_NAME) VALUES (2, 'Pedro', 'Suárez Antúnez');
INSERT INTO CUST_CUSTOMER (ID, NAME, LAST_NAME) VALUES (3, 'Alberto', 'Fuentes Guerrero');
INSERT INTO CUST_CUSTOMER (ID, NAME, LAST_NAME) VALUES (4, 'José', 'García Pérez');
INSERT INTO CUST_CUSTOMER (ID, NAME, LAST_NAME) VALUES (5, 'Luis', 'Albiol ');
INSERT INTO CUST_CUSTOMER (ID, NAME, LAST_NAME) VALUES (6, 'Félix', 'Benavente Zambrano');
INSERT INTO CUST_CUSTOMER (ID, NAME, LAST_NAME) VALUES (7, 'Cristina', 'Sánchez López');
INSERT INTO CUST_CUSTOMER (ID, NAME, LAST_NAME) VALUES (8, 'Lucía', 'Pérez Cordero');
INSERT INTO CUST_CUSTOMER (ID, NAME, LAST_NAME) VALUES (9, 'Irene', 'Fernández Saavedra');
INSERT INTO CUST_CUSTOMER (ID, NAME, LAST_NAME) VALUES (10, 'Ángela', 'Álvarez Ventura');